development:
  dialect: "sqlite3"
  database: /root/blog_app_development.sqlite

test:
  dialect: "sqlite3"
  database: /root/blog_app_test.sqlite

production:
  url: {{envOr "DATABASE_URL" "mysql://blog_app:blog_app@mysql-0.mysql/blog_app_production"}}
