development:
  dialect: "sqlite3"
  database: /root/blog_app_development.sqlite

test:
  dialect: "sqlite3"
  database: /root/blog_app_test.sqlite

production:
  dialect: "sqlite3"
  database: /root/blog_app_production.sqlite
